# Generated by Django 4.0.1 on 2022-01-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
