# Generated by Django 4.0.1 on 2022-01-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='ha'),
            preserve_default=False,
        ),
    ]
